### PR TITLE
Propagate worker errors to stream controller in Consumer

### PR DESCRIPTION
**Pull request by pulyaevskiy**
Fix for #3 .

### CODE REVIEW

**Comment by pulyaevskiy** [comment]
@butlermatt could you please verify this resolves your issue from #3?

You can temporarily switch your dependency to this branch with:

``` yaml
dependencies:
  kafka:
    git: 
      url: https://github.com/pulyaevskiy/dart-kafka.git
      ref: handle-errors-in-consumer-stream
```

**Comment by butlermatt** [comment]
Sure I'll try this a little later. I did implement a different work around temporary but I'll try this branch soon. Possibly later this evening otherwise over the weekend

**Comment by pulyaevskiy** [comment]
@butlermatt sure, no rush! Thanks again for your feedback, really appreciate it!

**Comment by butlermatt** [comment]
@pulyaevskiy Looks good now thanks. It's throwing an error I'm able to catch and handle.

**Comment by pulyaevskiy** [comment]
Thanks, merged.

**Pull request merged**
